//	PROJECT:        EveIndustrialAssistant (EIA)
//	AUTHORS:        Adam Antinoo - adamantinoo.git@gmail.com
//	COPYRIGHT:      (c) 2013-2014 by Dimensinfin Industries, all rights reserved.
//	ENVIRONMENT:		Android API11.
//	DESCRIPTION:		Application helper for Eve Online Industrialists. Will help on Minery and mainly on Manufacture.

package org.dimensinfin.evedroid.core;

// - IMPORT SECTION .........................................................................................
import java.util.Vector;

import org.dimensinfin.android.mvc.activity.PagerFragment;
import org.dimensinfin.android.mvc.activity.TitledFragment;
import org.dimensinfin.eveonline.neocom.R;

import android.app.Fragment;
import android.app.FragmentManager;
import android.support.v13.app.FragmentPagerAdapter;

// - CLASS IMPLEMENTATION ...................................................................................
public class EvePagerAdapter extends FragmentPagerAdapter {
	// - S T A T I C - S E C T I O N ..........................................................................

	// - F I E L D - S E C T I O N ............................................................................
	private final Vector<TitledFragment>	_fragments	= new Vector<TitledFragment>();
	private int														_pagerid		= R.id.pager;

	// - C O N S T R U C T O R - S E C T I O N ................................................................
	public EvePagerAdapter(final FragmentManager fm) {
		super(fm);
	}

	public EvePagerAdapter(final FragmentManager fm, final int pagerid) {
		super(fm);
		this._pagerid = pagerid;
	}

	// - M E T H O D - S E C T I O N ..........................................................................
	public void addPage(final TitledFragment fragNew) {
		if (null != fragNew) this._fragments.add(fragNew);
		notifyDataSetChanged();
	}

	@Override
	public int getCount() {
		return this._fragments.size();
	}

	/**
	 * Return the fragment internal identifier generated by the FragmentPager. This is a composed string from
	 * some fields that have to be informed to this adapter.
	 * 
	 * @param position
	 *          the page position I want to get the identification
	 * @return
	 */
	public String getFragmentId(final int position) {
		return "android:switcher:" + this._pagerid + ":" + getItemId(position);
	}

	@Override
	public Fragment getItem(final int position) {
		final Fragment frag = new PagerFragment();
		// Check if the requested position is available.
		if (position >= getCount()) return frag;
		return this._fragments.get(position);
	}

	public String getSubTitle(final int position) {
		return ((TitledFragment) getItem(position)).getSubtitle();
	}

	public String getTitle(final int position) {
		return ((TitledFragment) getItem(position)).getTitle();
	}

	public Fragment getInitialPage() {
		return getItem(0);
	}
}

// - UNUSED CODE ............................................................................................
