package org.dimensinfin.eveonline.neocom.core;

public enum EEvents {
	EVENTSTRUCTURE_NEWDATA, EVENTSTRUCTURE_DOWNLOADDATA, EVENTSTRUCTURE_DELETEDATA, EVENTSTRUCTURE_REFRESHDATA,
	EVENTCONTENTS_ACTIONEXPANDCOLLAPSE, EVENTCONTENTS_ACTIONMODIFYDATA,
	EVENTADAPTER_REQUESTNOTIFYCHANGES
}
