//	PROJECT:        EVEIndustrialist (EVEI)
//	AUTHORS:        Adam Antinoo - adamantinoo.git@gmail.com
//	COPYRIGHT:      (c) 2013-2014 by Dimensinfin Industries, all rights reserved.
//	ENVIRONMENT:		Android API11.
//	DESCRIPTION:		Application helper for Eve Online Industrialists. Will help on Industry and Manufacture.

package org.dimensinfin.eveonline.neocom.part;

// - IMPORT SECTION .........................................................................................
import java.util.ArrayList;

import org.dimensinfin.android.mvc.core.AbstractHolder;
import org.dimensinfin.eveonline.neocom.connector.AppConnector;
import org.dimensinfin.eveonline.neocom.constant.AppWideConstants;
import org.dimensinfin.eveonline.neocom.enums.EIndustryGroup;
import org.dimensinfin.eveonline.neocom.industry.EJobClasses;
import org.dimensinfin.eveonline.neocom.industry.IJobProcess;
import org.dimensinfin.eveonline.neocom.industry.JobManager;
import org.dimensinfin.eveonline.neocom.industry.Resource;
import org.dimensinfin.eveonline.neocom.interfaces.IItemPart;
import org.dimensinfin.eveonline.neocom.model.EveLocation;
import org.dimensinfin.eveonline.neocom.model.NeoComBlueprint;
import org.dimensinfin.eveonline.neocom.render.BlueprintResourceRender;
import org.dimensinfin.eveonline.neocom.render.OutputBlueprintRender;
import org.dimensinfin.eveonline.neocom.render.OutputResourceRender;
import org.dimensinfin.eveonline.neocom.render.Resource4MarketOrderRender;
import org.dimensinfin.eveonline.neocom.render.ResourceRender;
import org.dimensinfin.eveonline.neocom.render.SkillResourceRender;
import org.dimensinfin.eveonline.neocom.storage.AppModelStore;
import org.joda.time.DateTime;

import android.text.Html;
import android.text.Spanned;
import android.util.Log;
import android.view.View;
import android.view.View.OnClickListener;

// - CLASS IMPLEMENTATION ...................................................................................
public class ResourcePart extends ItemPart implements IItemPart, OnClickListener {
	// - S T A T I C - S E C T I O N
	// ..........................................................................
	private static final long	serialVersionUID	= -8085543451527813221L;
	// private double _balance = 0.0;

	// - F I E L D - S E C T I O N
	// ............................................................................
	private IJobProcess				process						= null;

	// - C O N S T R U C T O R - S E C T I O N
	// ................................................................
	public ResourcePart(final Resource node) {
		super(node);
		item = node.getItem();
		this.setRenderMode(AppWideConstants.rendermodes.RENDER_RESOURCECOMPONENTJOB);
	}

	// - M E T H O D - S E C T I O N
	// ..........................................................................
	/**
	 * Shows the icon for manufacture and the manufacture calculated cost for this item if can be calculated.
	 * NOt all item types can have this value so the display has to reflect that. If the cost of manufacture is
	 * less that the best sell price then the price is shown in green and the sell multiplier is added to the
	 * price. If the manufacture cost is greater than the sell price it is shown in red.
	 * 
	 * @return
	 */
	public String display_manufactureCost() {
		double cost = this.getJobProcess().getJobCost();
		// double sellprice = ;
		String secColor = "#F62217";
		if (cost < this.getSellerPrice()) {
			secColor = "#6CC417";
		}
		StringBuffer htmlPrice = new StringBuffer();
		htmlPrice.append("<font color='").append(secColor).append("'>").append(this.generatePriceString(cost, true, true))
				.append("</font>");
		return this.generatePriceString(cost, true, true);
	}

	/**
	 * The invention is not generated by the T2 blueprint but by the T1 branch. So first locate the blueprints
	 * that generate this module. But this applies to T2 blueprints only. So be aware of that before doing any
	 * processing. Or should be the caller the one to deal with this limitation?
	 */
	public String get_inventionCost() {
		// Locate T1 blueprints.
		ArrayList<Integer> ids = AppConnector.getDBConnector()
				.searchInventionableBlueprints(Integer.valueOf(this.getCastedModel().getTypeID()).toString());
		// Get access to the Invention process.
		IJobProcess inventionProcess = JobManager.generateJobProcess(this.getPilot(), new NeoComBlueprint(ids.get(0)),
				EJobClasses.INVENTION);
		return this.generatePriceString(inventionProcess.getJobCost(), true, true);
	}

	public String get_price() {
		return this.generatePriceString(this.getSellerPrice(), true, true);
	}

	public Spanned get_profit() {
		double oneprofit = this.getBuyerPrice() - this.getManufactureCost();
		double profit = oneprofit * this.getCastedModel().getQuantity();
		String secColor = "#6CC417";
		if (profit < 0) {
			secColor = "#F62217";
		}
		StringBuffer htmlPrice = new StringBuffer("<font color='").append(secColor).append("'>")
				.append(this.generatePriceString(profit, true, true)).append("</font>");
		return Html.fromHtml(htmlPrice.toString());
	}

	public double getBalance() {
		return this.getCastedModel().getQuantity() * this.getSellerPrice();
	}

	public Resource getCastedModel() {
		return (Resource) this.getModel();
	}

	public EveLocation getHighestBuyerLocation() {
		return this.getCastedModel().getItem().getHighestBuyerPrice().getLocation();
	}

	public double getHighestBuyerPrice() {
		return this.getCastedModel().getItem().getHighestBuyerPrice().getPrice();
	}

	public EIndustryGroup getIndustryGroup() {
		return this.getCastedModel().getItem().getIndustryGroup();
	}

	/**
	 * Gets the cost to manufacture a single run of an item. To calculate this it will use the corresponding
	 * process.
	 * 
	 * @return
	 */
	public double getManufactureCost() {
		int moduleid = this.getCastedModel().getTypeID();
		int blueprintid = AppConnector.getDBConnector().searchBlueprint4Module(moduleid);
		IJobProcess process = JobManager.generateJobProcess(AppModelStore.getSingleton().getPilot(),
				new NeoComBlueprint(blueprintid), EJobClasses.MANUFACTURE);
		return process.getJobCost();
	}

	public int getQuantity() {
		return this.getCastedModel().getQuantity();
	}

	public DateTime getRegistrationDate() {
		return this.getCastedModel().getRegistrationDate();
	}

	// FIXME This was removed from the implementation while the migration to new eveapi. reimplement
	public int getSkillLevel() {
		return 5;
		//		return getPilot().getSkillLevel(getCastedModel().getTypeID());
	}

	// public AbstractAndroidPart setBalance(final double balance) {
	// _balance = balance;
	// return this;
	// }

	public void onClick(final View v) {
		Log.i("EVEI", ">> ResourcePart.onClick");
		// Activate only for some elements.
		// REFACTOR Access to ItemDetail removed until revision
		if ((this.getRenderMode() == AppWideConstants.rendermodes.RENDER_RESOURCECOMPONENTJOB)
				|| (this.getRenderMode() == AppWideConstants.rendermodes.RENDER_RESOURCEOUTPUTJOB)) {
			//			Intent intent = new Intent(this.getActivity(), ItemDetailsActivity.class);
			//			intent.putExtra(AppWideConstants.extras.EXTRA_EVECHARACTERID, this.getPilot().getCharacterID());
			//			intent.putExtra(AppWideConstants.extras.EXTRA_EVEITEMID, this.getCastedModel().getTypeID());
			//			this.getActivity().startActivity(intent);
		}
		Log.i("EVEI", "<< ResourcePart.onClick");
	}

	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer("ResourcePart [");
		buffer.append("Qty:").append(this.getCastedModel().getQuantity()).append(" ");
		buffer.append(super.toString());
		buffer.append("]");
		return buffer.toString();
	}

	@Override
	protected void initialize() {
		item = this.getCastedModel().item;
	}

	@Override
	protected AbstractHolder selectHolder() {
		if (this.getRenderMode() == AppWideConstants.rendermodes.RENDER_RESOURCESKILLJOB)
			return new SkillResourceRender(this, _activity);
		if (this.getRenderMode() == AppWideConstants.rendermodes.RENDER_RESOURCEOUTPUTJOB)
			return new OutputResourceRender(this, _activity);
		if (this.getRenderMode() == AppWideConstants.rendermodes.RENDER_RESOURCEBLUEPRINTJOB)
			return new BlueprintResourceRender(this, _activity);
		if (this.getRenderMode() == AppWideConstants.rendermodes.RENDER_RESOURCECOMPONENTJOB)
			return new ResourceRender(this, _activity);
		if (this.getRenderMode() == AppWideConstants.rendermodes.RENDER_RESOURCEOUTPUTBLUEPRINT)
			return new OutputBlueprintRender(this, _activity);
		// if (getRenderMode() ==
		// AppWideConstants.rendermodes.RENDER_RESOURCESCHEDULEDSELL)
		// return new T2Mod4SellRender(this, _activity);
		if (this.getRenderMode() == AppWideConstants.rendermodes.RENDER_MARKETORDERSCHEDULEDSELL)
			return new Resource4MarketOrderRender(this, _activity);
		throw new RuntimeException("E> resourcePart. Undefined Render variant.");
	}

	private IJobProcess getJobProcess() {
		if (null == process) {
			int moduleid = this.getCastedModel().getTypeID();
			int blueprintid = AppConnector.getDBConnector().searchBlueprint4Module(moduleid);
			process = JobManager.generateJobProcess(AppModelStore.getSingleton().getPilot(), new NeoComBlueprint(blueprintid),
					EJobClasses.MANUFACTURE);
		}
		return process;
	}
}

// - UNUSED CODE
// ............................................................................................
